export enum NotificationActionTypes {
  INFO = "[Notifier] info",
  SUCCESS = "[Notifier] success",
  ERROR = "[Notifier] error",
  WARNING = "[Notifier] warning",
}

export enum AuthActionTypes {
  AUTH_LOGOUT = "AUTH_LOGOUT",
  FETCH_LOGIN_DETAILS = "FETCH_LOGIN_DETAILS",
  FETCH_LOGIN_DETAILS_SUCCESS = "FETCH_LOGIN_DETAILS_SUCCESS",
  FETCH_LOGIN_DETAILS_ERROR = "FETCH_LOGIN_DETAILS_ERROR",

  FETCH_USER_DETAILS = "FETCH_USER_DETAILS",
  FETCH_USER_DETAILS_SUCCESS = "FETCH_USER_DETAILS_SUCCESS",
  FETCH_USER_DETAILS_ERROR = "FETCH_USER_DETAILS_ERROR",
}

export enum UserRegActionTypes {
  POST_USER_DETAILS = "POST_USER_DETAILS",
  POST_USER_DETAILS_SUCCESS = "POST_USER_DETAILS_SUCCESS",
  POST_USER_DETAILS_ERROR = "POST_USER_DETAILS_ERROR",
}

export enum VideoActionTypes {
  CURRENT_VIDEO = "CURRENT_VIDEO",
  VIDEO_DIMENSION = "VIDEO_DIMENSION",

  FETCH_ALL_VIDEOS = "FETCH_ALL_VIDEOS",
  FETCH_ALL_VIDEOS_SUCCESS = "FETCH_ALL_VIDEOS_SUCCESS",
  FETCH_ALL_VIDEOS_ERROR = "FETCH_ALL_VIDEOS_ERROR",
}
